# see https://www.gitpod.io/docs/config-gitpod-file

tasks:
  - name: download
    init: |
      curl -sSOL https://archive.ics.uci.edu/ml/machine-learning-databases/00279/SUSY.csv.gz && \
      gunzip SUSY.csv.gz
  - name: setup
    init: |
      python -m venv /workspace/.venv && \
      source /workspace/.venv/bin/activate && \
      pip install --upgrade pip && \
      pip install -r requirements.txt && \
      curl -sL --http1.1 https://cnfl.io/cli | sh -s -- -b /workspace/bin && \
      /workspace/bin/confluent version
    command: |
      ln -s /workspace/bin/confluent /home/gitpod/.local/bin/confluent
      source /workspace/.venv/bin/activate
